### ISSUE TITLE
牌譜のリストをダウンロードうまくできない

### ISSUE THREAD

**Issue by caisj2016** [majaneye/JANTAMA#2]
友人戦データダウンロードしたいですか、うまくできないそうです

**Comment by majaneye** [comment]
ダウンロードの手順はどちらを参考にされたでしょうか？

1.
https://github.com/majaneye/JANTAMA/wiki/%E7%89%8C%E8%AD%9C%E3%81%AE%E4%B8%80%E6%8B%AC%E3%83%80%E3%82%A6%E3%83%B3%E3%83%AD%E3%83%BC%E3%83%89

2.
https://wikiwiki.jp/majsoul-api/%E7%89%8C%E8%AD%9C%E3%82%92%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AB%E4%BF%9D%E5%AD%98%E3%81%99%E3%82%8B%E3%81%AB%E3%82%83

**Comment by caisj2016** [comment]
1.友人戦データダウンロードできます、ファイル中身はデータがありません
[mahjongsoul_yuujin_uuid_list.txt](https://github.com/majaneye/JANTAMA/files/9270083/mahjongsoul_yuujin_uuid_list.txt)

**Comment by majaneye** [comment]
状況を教えていただいて、ありがとうございます。

段位戦はダウンロードできていますか？

**Comment by majaneye** [comment]
友人戦の記録がないため、検証できていないのですが
牌譜リストダウンロード用のパラメータの指定が間違っている可能性があります。（スクリプトの誤り）

友人戦をやって試してみるので、1日ほどお待ちください。

**Comment by caisj2016** [comment]
> 状況を教えていただいて、ありがとうございます。
> 
> 段位戦はダウンロードできていますか？

段位戦と大会戦、大丈夫です。

**Comment by majaneye** [comment]
お待たせしてすみません、こちらのWikiを修正しました。
友人戦の場合は"paifulist(1)"としてください。

https://github.com/majaneye/JANTAMA/wiki/%E7%89%8C%E8%AD%9C%E3%81%AE%E4%B8%80%E6%8B%AC%E3%83%80%E3%82%A6%E3%83%B3%E3%83%AD%E3%83%BC%E3%83%89

**Comment by caisj2016** [comment]
ご対応ありがとうございます。
